---
title: "iSSA notes"
author: "Vincent Pan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc_float: true
    toc: true 
    toc_depth: 2 
    number_sections: true
    code_folding: show
    highlight: tango
    theme: default
---


For the distribution of turn angles $\theta$, we consider a special case of the the generalized von Mises distribution (Gatto and Jammalamadaka 2007) which has the density function,


$$
P(\theta;\kappa_1, \kappa_2) = \frac{\exp(\kappa_1 \cos(\theta + \pi) + \kappa_2 \cos(2\theta ))}{
\int_0^{2 \pi} \exp(\kappa_1 \cos(\theta + \pi) + \kappa_2 \cos(2\theta )) d\theta
}
$$


We generated random draws from this distribution using the ratio-of-uniforms algorithm from Gatto (2007).

It can be shown that the probability of observing a turn angle $\theta$ can be expressed as an exponential function of some linear combination of $\cos(\theta + \pi)$ and $\cos(2\theta)$,


$$
\ln(P(\theta; \kappa_1, \kappa_2)) \propto \kappa_1 \cos(\theta + \pi) + \kappa_2 \cos(2\theta)
$$


Thus, given the likelihood function $(3)$ the maximum likelihood estimate of the regression coefficients $\beta_{\kappa_1}$ and $\beta_{\kappa_2}$ can be seen as an estimator of the bias of $\kappa_1$ and $\kappa_2$ in the tentative distributions respectively.


$$
\begin{align}
\tag{3}
\prod_{t=3}^{T} \frac{\exp(\beta_{\kappa_1} \cos(\theta_t + \pi) + \beta_{\kappa_2} \cos(2\theta_t))}{\sum_{i=1}^S\exp(\beta_{\kappa_1} \cos(\theta_{i,t}' + \pi) + \beta_{\kappa_2} \cos(2\theta_{i,t}'))}
\end{align}
$$


Here, $T$ is a set of spatial positions with turn angle $\theta_t$. $\theta_i'$ is an element of a set $S$ of randomly generated available turn angles.


For the distribution of step lengths $l$, we consider the zero inflated (hurdle) gamma distribution, an extension to the gamma distribution commonly used to model step length to handle transitions when the caterpillar remains stationary. It has density function,


$$
P(l; \varphi, k, q) = 
\begin{cases} 
\varphi & \text{for } l = 0 \\
(1-\varphi) \frac{l^{k-1} \exp(-l/q)}{q^k \Gamma(k)} & \text{for } l > 0
\end{cases}
$$


$1-\varphi$ is the movement probability, and $k$ and $q$ are the shape and scale parameters respectively. Avgar et al. (2015) has showed that including $l$ and $\ln(l)$ in conditional logistic regression can allow the use of their corresponding regression coefficients to update the $k$ and $q$ parameters, much like the above procedure. With the zigamma distribution, we include $l\cdot\text{moved}$ and $\ln(l)\cdot\text{moved}$ in place of $l$ and $\ln(l)$, where $\text{moved}$ is a binary variable indicating whether movement has occurred ($l > 0$). This has the effect of only using movement telemetry data to estimate the shape and scale parameters. The same goes for the estimation of $\kappa_1$ and $\kappa_2$ when we use zigamma. Updating te $p$ parameter is a bit trickier. Once we have fitted a first pass of the issa model then updated the movement parameters $k$, $q$, $\kappa_1$, and $\kappa_2$, we can repeat the random step simulation and conditional logistic regression fitting, arriving at a final estimate of $\beta_{\text{moved}}$. This coefficient can then be updated via,


$$
\hat{\varphi}=\text{logit}^{-1}(\text{logit}(\varphi_{0}) - \beta_{\text{moved}})
$$


Our integrated step selection analysis model has the basic formulation,

$$
\begin{align}
y \sim \ & \text{Bernouli}(p) \\
\text{logit}(p) = \ & \underbrace {X\beta}_{\text{Movement free habitat selection}} \ + \\ 
& \underbrace{\beta_{\text{moved}} \ \text{Moved} + \beta_{k} \ l\cdot\text{Moved} + \beta_{q} \ \ln(l)\cdot\text{Moved} }_{\text{Selection free step length}} \ +\\ 
& \underbrace{\beta_{\kappa_1} \ \cos(\theta + \pi)\cdot\text{Moved} + \beta_{\kappa_2} \ \cos(2\theta)\cdot\text{Moved}}_{\text{Selection free turn angle}} \ + \\
& \underbrace{\alpha_{\text{stratum(i)}}}_{\text{Step matching}}
\end{align}
$$







Instead of a zigamma distribution, a better approximation of the data generating process is a zero censored gamma distribution (hereafter as zCG). $l^*$ correspond to the minimum threshold of step length to be considered as movement.


$$
P(l; l^*, k, q) = 
\begin{cases} 
G(l^*; k, q) & \text{for } l \leq l^* \\
(1-G(l^*; k, q))\frac{l^{k-1} \exp(-l/q)}{q^k \Gamma(k)} & \text{for } l > l^*
\end{cases}
$$
$$
G(l; k, q) = \int_{0}^{l} \frac{l^{k-1} \exp(-l/q)}{q^k \Gamma(k)}
$$


$$
\ln(P(l; l^*, k, q)) \propto (k-1) \ \ln(l) - \frac{1}{q} l
$$















