# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

g_genvonmisesC <- function(omega, kappa1, kappa2) {
    .Call(`_spat1f_g_genvonmisesC`, omega, kappa1, kappa2)
}

propose_genvonmises <- function(n, a, kappa1, kappa2) {
    .Call(`_spat1f_propose_genvonmises`, n, a, kappa1, kappa2)
}

rgenvonmisesC <- function(n, kappa1, kappa2, max_try = 1000L) {
    .Call(`_spat1f_rgenvonmisesC`, n, kappa1, kappa2, max_try)
}

iouC <- function(img1, img2) {
    .Call(`_spat1f_iouC`, img1, img2)
}

mask_insersectC <- function(img1, img2) {
    .Call(`_spat1f_mask_insersectC`, img1, img2)
}

read_valueC <- function(x, y, max_x, max_y, img) {
    .Call(`_spat1f_read_valueC`, x, y, max_x, max_y, img)
}

add_random_stepsC <- function(n_draws, x_start, y_start, direction_start, sl_rand, ta_rand, index, rss_coef_exp, ref_grid_flat) {
    .Call(`_spat1f_add_random_stepsC`, n_draws, x_start, y_start, direction_start, sl_rand, ta_rand, index, rss_coef_exp, ref_grid_flat)
}

add_random_steps_iterateC <- function(n, n_draws, x_start, y_start, direction_start, diet_start, sl_rand, ta_rand, rss_coef, same_move, ref_grid_flat) {
    .Call(`_spat1f_add_random_steps_iterateC`, n, n_draws, x_start, y_start, direction_start, diet_start, sl_rand, ta_rand, rss_coef, same_move, ref_grid_flat)
}

pick_new_state <- function(state, transition_mat) {
    .Call(`_spat1f_pick_new_state`, state, transition_mat)
}

add_random_steps_iterate_statesC <- function(n, n_draws, x_start, y_start, direction_start, diet_start, state_start, sl_rand, ta_rand, rss_coef, transition_mat, same_move, ref_grid_flat, max_x = 1000, max_y = 1000, dim_x = 12, dim_y = 12) {
    .Call(`_spat1f_add_random_steps_iterate_statesC`, n, n_draws, x_start, y_start, direction_start, diet_start, state_start, sl_rand, ta_rand, rss_coef, transition_mat, same_move, ref_grid_flat, max_x, max_y, dim_x, dim_y)
}

flatten_xy <- function(x, y, max_x = 1000, max_y = 1000, dim_x = 12, dim_y = 12) {
    .Call(`_spat1f_flatten_xy`, x, y, max_x, max_y, dim_x, dim_y)
}

pick_new_theta_xy <- function(sl_rand, ta_rand, index, n, direction_start, x_start, y_start, max_x = 1000, max_y = 1000, dim_x = 12, dim_y = 12) {
    .Call(`_spat1f_pick_new_theta_xy`, sl_rand, ta_rand, index, n, direction_start, x_start, y_start, max_x, max_y, dim_x, dim_y)
}

